name = "FLOWFMM"
uuid = "ce07d0d3-2b9f-49ba-89eb-12c800257c85"
authors = ["rymanderson <rymanderson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
